trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  displayName: Build
  inputs:
    gradleWrapperFile: 'gradlew'
    options: -b "build-11.gradle"
    tasks: clean build

- task: PublishPipelineArtifact@1
  displayName: "Publish Build Directory"
  inputs:
    targetPath: "$(Build.SourcesDirectory)/build/libs/java11"
    artifact: output
